name: flutter_project_places
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: 3.4.1
  collection: 1.19.1
  cupertino_icons: ^1.0.8 #для ios иконки
  dio: 5.8.0+1 #для работы с сетью
  drift: 2.27.0 #для работы с бд
  drift_flutter: 0.2.4
  # equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_svg: 2.2.0
  # freezed_annotation: ^2.4.1
  json_annotation: 4.9.0
  path: 1.9.1 #для работы с внутренним хранилищем
  path_provider: 2.1.5
  provider: 6.1.5 #для передачи зависимостей
  # retrofit: ^4.6.0
  rxdart: 0.28.0 #СЛОЖНЫЙ ПОИСК
  shared_preferences: ^2.5.3 #хранилище данных (темы)
  sqlite3_flutter_libs: 0.5.34 #чтоб правильно работал дрифт

dev_dependencies:
  build_runner: ^2.5.4 #для генерации
  drift_dev: 2.27.0 #для генерации
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 #было тут
  # freezed: ^2.4.1
  json_serializable: ^6.9.5
  # retrofit_generator: ^9.6.0
  # surf_dcm_presets: 1.0.0
  # surf_lint_rules: 4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/catalog/
    - assets/images/
    - assets/json/
    # - lib/assets/images/
    # - lib/assets/strings/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
